# coding: utf-8

"""
    ITM TA3 API

    This is the specification of the TA3 API for In The Moment (ITM).  Currently, the Evaluation API for TA2 supports functionality for the Phase 1 Evaluation.  The API is based on the OpenAPI 3.0.3 specification.

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ActionTypeEnum(str, Enum):
    """
    An action type [recognized by the ADM Server](https://github.com/NextCenturyCorporation/itm-evaluation-client?tab=readme-ov-file#available-actions)
    """

    """
    allowed enum values
    """
    APPLY_TREATMENT = 'APPLY_TREATMENT'
    CHECK_ALL_VITALS = 'CHECK_ALL_VITALS'
    CHECK_BLOOD_OXYGEN = 'CHECK_BLOOD_OXYGEN'
    CHECK_PULSE = 'CHECK_PULSE'
    CHECK_RESPIRATION = 'CHECK_RESPIRATION'
    DIRECT_MOBILE_CHARACTERS = 'DIRECT_MOBILE_CHARACTERS'
    END_SCENE = 'END_SCENE'
    MESSAGE = 'MESSAGE'
    MOVE_TO = 'MOVE_TO'
    MOVE_TO_EVAC = 'MOVE_TO_EVAC'
    SEARCH = 'SEARCH'
    SITREP = 'SITREP'
    TAG_CHARACTER = 'TAG_CHARACTER'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ActionTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


