# coding: utf-8

"""
    ITM TA3 API

    This is the specification of the TA3 API for In The Moment (ITM).  Currently, the Evaluation API for TA2 supports functionality for the Phase 1 Evaluation.  The API is based on the OpenAPI 3.0.3 specification.

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MissionTypeEnum(str, Enum):
    """
    enumeration of possible mission types
    """

    """
    allowed enum values
    """
    ATTACK = 'Attack'
    DEFEND = 'Defend'
    DELAY = 'Delay'
    PATROL = 'Patrol'
    RECONNAISSANCE = 'Reconnaissance'
    AMBUSH = 'Ambush'
    LISTENING_SLASH_OBSERVATION = 'Listening/Observation'
    DIRECT_ACTION = 'Direct Action'
    HOSTAGE_RESCUE = 'Hostage rescue'
    ASSET_TRANSPORT = 'Asset transport'
    SENSOR_EMPLACEMENT = 'Sensor emplacement'
    INTELLIGENCE_GATHERING = 'Intelligence gathering'
    CIVIL_AFFAIRS = 'Civil affairs'
    TRAINING = 'Training'
    SABOTAGE = 'Sabotage'
    SECURITY_PATROL = 'Security patrol'
    FIRE_SUPPORT = 'Fire support'
    NUCLEAR_DETERRENCE = 'Nuclear deterrence'
    EXTRACTION = 'Extraction'
    UNKNOWN = 'Unknown'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MissionTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


