# coding: utf-8

"""
    ITM TA3 API

    This is the specification of the TA3 API for In The Moment (ITM).  Currently, the Evaluation API for TA2 supports functionality for the Phase 1 Evaluation.  The API is based on the OpenAPI 3.0.3 specification.

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class ProbeResponses(BaseModel):
    """
    tag-specific probe responses (choices) for a tagged character
    """ # noqa: E501
    character_id: StrictStr = Field(description="A valid character ID from the scene")
    probe_id: StrictStr = Field(description="A valid probe_id from the appropriate TA1")
    minimal: StrictStr = Field(description="The probe response to send for a MINIMAL tag")
    delayed: StrictStr = Field(description="The probe response to send for a DELAYED tag")
    immediate: StrictStr = Field(description="The probe response to send for a IMMEDIATE tag")
    expectant: StrictStr = Field(description="The probe response to send for a EXPECTANT tag")
    __properties: ClassVar[List[str]] = ["character_id", "probe_id", "minimal", "delayed", "immediate", "expectant"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProbeResponses from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProbeResponses from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "character_id": obj.get("character_id"),
            "probe_id": obj.get("probe_id"),
            "minimal": obj.get("minimal"),
            "delayed": obj.get("delayed"),
            "immediate": obj.get("immediate"),
            "expectant": obj.get("expectant")
        })
        return _obj


