# coding: utf-8

"""
    ITM TA3 API

    This is the specification of the TA3 API for In The Moment (ITM).  Currently, the Evaluation API for TA2 supports functionality for the Phase 1 Evaluation.  The API is based on the OpenAPI 3.0.3 specification.

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MilitaryRankEnum(str, Enum):
    """
    the cross-branch military rank (paygrade)
    """

    """
    allowed enum values
    """
    E_MINUS_1 = 'E-1'
    E_MINUS_2 = 'E-2'
    E_MINUS_3 = 'E-3'
    E_MINUS_4 = 'E-4'
    E_MINUS_5 = 'E-5'
    E_MINUS_6 = 'E-6'
    E_MINUS_7 = 'E-7'
    E_MINUS_8 = 'E-8'
    E_MINUS_9 = 'E-9'
    E_MINUS_9_LEFT_PARENTHESIS_SPECIAL_RIGHT_PARENTHESIS = 'E-9 (special)'
    W_MINUS_1 = 'W-1'
    W_MINUS_2 = 'W-2'
    W_MINUS_3 = 'W-3'
    W_MINUS_4 = 'W-4'
    W_MINUS_5 = 'W-5'
    O_MINUS_1 = 'O-1'
    O_MINUS_2 = 'O-2'
    O_MINUS_3 = 'O-3'
    O_MINUS_4 = 'O-4'
    O_MINUS_5 = 'O-5'
    O_MINUS_6 = 'O-6'
    O_MINUS_7 = 'O-7'
    O_MINUS_8 = 'O-8'
    O_MINUS_9 = 'O-9'
    O_MINUS_10 = 'O-10'
    SPECIAL = 'Special'
    SPECIAL_LEFT_PARENTHESIS_NAVY_RIGHT_PARENTHESIS = 'Special (Navy)'
    SPECIAL_LEFT_PARENTHESIS_COAST_GUARD_RIGHT_PARENTHESIS = 'Special (Coast Guard)'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MilitaryRankEnum from a JSON string"""
        return cls(json.loads(json_str))


